name: Cache CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: prime-cache-aa85955
        id: prime-cache-aa85955
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-aa85955

      - name: Show cache result
        run: echo "Cache hit: ${{ steps.prime-cache-aa85955.outputs.cache-hit }}"
